# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Crypt Market Cap' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'SVProgressHUD'
pod 'Alamofire', '~> 4.5'
pod 'AlamofireObjectMapper', '~> 5.0'
pod 'SwiftyDrop', '~>4.0'
pod 'SwiftDate'

  # Pods for Crypt Market Cap

  target 'Crypt Market CapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Crypt Market CapUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
